image: eclipse-temurin:21-jdk

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build


build_mod:
  stage: build
  before_script:
    - apt update && apt install -y git
  script:
    - chmod +x ./gradlew
    - ./gradlew build --stacktrace
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week


workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
